### PR TITLE
4 sequential numbering

### LINKED ISSUE #4: Sequential numbering between pages
Hi @ignorantshr,

My team uses `MkDocs` to both publish a site and export a report as PDF (using [mkdocs-pdf-export-plugin](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin)).

I would like to have the numbering increment for each main page. That way, you can refer to specific sections in the PDF report.

Happy to work on a PR if you're interested in adding this feature?

### PR DESCRIPTION
**Pull request by timvink**
This closes #4 

It's quite a big PR:

- Adds sequential page numbers, turned on to True by default (I can change that if you want)
- Adds unit tests
- Refactors some of the code
- Added some user input validation. F.e. 
   - using multiple heading 1 levels in a page
   - using wrong options, f.e. `exclude` instead of `excludes`

Let me know if you want me to change or remove something.

### CODE REVIEW

**Comment by ignorantshr** [comment]
I don't think it's a problem.

> using multiple heading 1 levels in a page

We should not make "h1" special, it should be treated equally with other titles.

And could you please resolve the confilct?
```
plugins:
    - search
<<<<<<< 4-sequential-numbering
    - mkdocs-add-number-plugin:
        increment_pages: True
=======
    - add-number:
>>>>>>> maste
        strict_mode: False
        order: 1
```

**Comment by timvink** [comment]
> We should not make "h1" special, it should be treated equally with other titles.

Yes. but when within one page you have multiple headers, you need to account for that in the sequential pages. 

```html
# Header 1 page 1
# Second Heading 1 page 2
```
```html
# Header 1 page 2
```

Will render as 

```html
# 1. Header 1 page 1
# 2. Second Heading 1 page 2
```
```html
# 2. Header 1 page 2
```
But "2. Header 1 page 2" Should be "3. Header 1 page 2"

I have not implemented that logic yet.. 

Update: I replaced the error with a warning in https://github.com/ignorantshr/mkdocs-add-number-plugin/pull/10/commits/f4d9d523449f03d0df42616369c502f27d8e52e8. Shall I create a separate  issue to fix this? Otherwise the PR will become very big

**Comment by ignorantshr** [comment]
I will merge these your commits firstly, then you fix it, is it OK?

**Comment by timvink** [comment]
Yes. I have created #12 for that. We can release a new version to PyPi once we are happy with all the changes.

**Comment by pnavaro** [comment]
Thank you for this mkdocs plugin, but are you sure that this sequential numbering is working. I tried to build the dummy project in tests and all pages starts to one.

**Comment by timvink** [comment]
Yes, the `add-number` plugin always starts pages at one. To add sequential numbering we needed to change a lot (almost everything) in the plugin, so in the end we decided to remove sequential numbering from this plugin and I created a second plugin to do that. Have a look at [mkdocs-enumerate-headings-plugin](https://github.com/timvink/mkdocs-enumerate-headings-plugin)

**Comment by pnavaro** [comment]
It works very well thank you!  I am looking for a way to generate the whole table of contents. Perharps you know a plugin. I tried using pandas to generate the markdown file but links are not valid.

**Comment by timvink** [comment]
Have you seen https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins ? If you can't find what you're looking for, there might be an opportunity to build a new plugin ;)

**Pull request merged**
